# -*- coding: utf-8 -*-
"""app.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RbAAAm9AubXCLRLbnYKMBDHmTv9hMYps
"""

from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(
    title="Enterprise Customer Support GenAI Chatbot",
    description="RAG-based chatbot using FAISS and document grounding",
    version="1.0"
)

class ChatRequest(BaseModel):
    question: str

@app.post("/chat")
def chat(request: ChatRequest):
    """
    API wrapper for the RAG pipeline.
    Core logic is demonstrated and validated in rag_pipeline.ipynb.
    """
    return {
        "question": request.question,
        "answer": "RAG pipeline logic is demonstrated in rag_pipeline.ipynb"
    }

